sudo: false
language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - ./scripts/run-on-node-version.sh 12 "npm run test-with-coverage"
